### ISSUE TITLE
Getting failed to find Premain-class manifest attribute error

### ISSUE THREAD

**Issue by sharmaishan1729** [nuxeo/gatling-report#1]
I am getting the below error
Command : java -jar gatling-report-1.0-20151221.095143-6-capsule-fat.jar
Error:
Failed to find Premain-Class manifest attribute in F:\GatlingReport\gatling-report-1.0-20151221.095143-6-capsule-fat.jar
Error occurred during initialization of VM
agent library failed to init: instrument

**Comment by maruphani** [comment]
Even am seeing the same without building and just downloading the jar or by packaging the github project, can you please provide fix for same?

**Comment by sharmaishan1729** [comment]
Any updates?

**Comment by bdelbosc** [comment]
Hi, 

Sorry for the delay I didn't see the first notifications.

Under linux I can not reproduce event on a new account:
```
wget "https://maven-eu.nuxeo.org/nexus/service/local/artifact/maven/redirect?r=public-snapshots&g=org.nuxeo.tools&a=gatling-report&v=1.0-SNAPSHOT&e=jar&c=capsule-fat" -O gatling-report-1.0-20160118.082004-12-capsule-fat.jar
java -jar gatling-report-1.0-20160118.082004-12-capsule-fat.jar -h
Usage: java -jar gatling-report.jar [options] SIMULATION.LOG...
  Options:
    --apdex-threshold, -T
       Apdex thresold, the response time in second above which the request
...
java -version
*java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
```
A quick test with Java 1.7.0_91 works fine also.

Could you provide more information:
- JVM used
- the content of your ~/.capsule/apps directory

If possible!
- Can you use an alternative log4j.xml,  take example from the one in the source and update the unix path maybe:
```
java -jar ... -Dlog4j.configuration=mylog4j.xml
```
- Check under linux if it works

Thanks
ben

**Comment by sharmaishan1729** [comment]
Hello Ben,
I tried to run on my Mac it works fine but not on my windows box.

JVM - 1.8.0_66
Windows - Windows 10.

-Ishan

**Comment by ManiAzizzadeh** [comment]
Hi all,

I managed to solve this by modifying the configuration for the maven assembly plugin in the pom.xml when building on Windows, I changed the version of the plugin and added an entry for Premain-Class:

```
<plugin>
        <artifactId>maven-assembly-plugin</artifactId>
        <version>2.5</version>
        <configuration>
          <archive>
            <manifest>
              <mainClass>Capsule</mainClass> 
            </manifest>
            <manifestEntries>
              <Application-Class>App</Application-Class>
		<Premain-Class>Capsule</Premain-Class>
            </manifestEntries>
          </archive>
          <descriptors>
            <descriptor>src/main/assembly/capsule-fat.xml</descriptor>
          </descriptors>
        </configuration>
        <executions>
          <execution>
            <id>make-assembly</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

Thanks to Ben for this really nice tool which allows me among other things to get reports for times when I need to cancel the gatling run or when the report generation fails for other reasons.

**Comment by bdelbosc** [comment]
Yes thanks !
I have commited a fix based on your change, can you give a try with the latest snaphot from 
https://maven-eu.nuxeo.org/nexus/#nexus-search;quick~gatling-report
to see if it works under Windows ?

Regards
ben

**Comment by ManiAzizzadeh** [comment]
Works perfectly:

```
> java -jar gatling-report-1.0-20160211.163920-13-capsule-fat.jar -h
Usage: java -jar gatling-report.jar [options] SIMULATION.LOG...
```

Think we can close this one now. :+1:

**Comment by bdelbosc** [comment]
Thanks !
