### ISSUE TITLE
Ability to display content of (failed) requests

### ISSUE THREAD

**Issue by PAX523** [nuxeo/gatling-report#16]
The report allows me to inspect the details of failed requests. I can even see the occurred exception and the destination host. Is there also a way to display the request's content?

**Comment by bdelbosc** [comment]
Hi, no if you want to see request and response for failure you have to update your logback.xml:

```        <!-- Uncomment for logging ALL HTTP request and responses -->
        <!--    <logger name="io.gatling.http.ahc" level="TRACE" /> -->
        <!--    <logger name="io.gatling.http.response" level="TRACE" /> -->
        <!-- Uncomment for logging ONLY FAILED HTTP request and responses -->
        <logger name="io.gatling.http.ahc.AsyncHandler" level="DEBUG" />
        <logger name="io.gatling.http.ahc.AsyncHandlerActor" level="DEBUG" />
        <logger name="io.gatling.http.response" level="DEBUG" />
```
Regards

**Comment by PAX523** [comment]
Okay, thanks for this hint.

In my opinion it would be reasonable to track request bodies for at least failed requests in the report.
