### ISSUE TITLE
Fork created

### ISSUE THREAD

**Issue by DennisRippinger** [nuxeo/gatling-report#21]
I created a fork of this project. It uses the calculation logic and encapsulate it within a maven plugin and is hosted here: https://github.com/DennisRippinger/gatling-reporter.

The code is also under LGPL 2.1 and the original code has the same Licence header with the same authors mentioned. I hope to be compliant with the license terms, but please have a look if it fits your intended use.

**Comment by bdelbosc** [comment]
forks happen, that's life, no worries.
