### ISSUE TITLE
Difference in the request count

### ISSUE THREAD

**Issue by rkarthikeyan5** [nuxeo/gatling-report#3]
Hi, I created a report with the same `simulation.log` with using this tool and compared it with the standard gatling report.  What I found was the total requests were very widely different between the two reports.  I had the original gatling report showing around 80K requests (which was close to the number of lines in the simulation.log itself).  But when I pulled a report from this tool, it showed ~30k requests.

**Comment by bdelbosc** [comment]
Hi, can you give access to the simulation.log ?

**Comment by rkarthikeyan5** [comment]
Here is the log file (converted to txt)
[simulation.txt](https://github.com/nuxeo/gatling-report/files/348285/simulation.txt)

**Comment by bdelbosc** [comment]
Thanks, indeed there are some backslash in your simulation.log file they are part of KO error message (regex failing).
Apparently there is a known bug in the [opencsv lib](https://sourceforge.net/p/opencsv/bugs/125/) that prevent to parse properly the rest of the file.
I will see what I can do, in the meantime you can remove these requests from the simulation file with:
`grep -v "\\\\" simulation.log > simulation-fix.log`
and you will find the same of successful requests.
Thanks again for reporting.
ben

**Comment by rkarthikeyan5** [comment]
Thank you for your feedback!  Much appreciated.

**Comment by bdelbosc** [comment]
FYI, I just changed the CSV Reader lib and it works now.
