### ISSUE TITLE
Calling System.exit()

### ISSUE THREAD

**Issue by stolp** [nuxeo/gatling-report#5]
We are using [exec-maven-plugin](http://www.mojohaus.org/exec-maven-plugin/) with the` java` goal to call gatling-report.

As gatling-report is calling `System.exit()` after creating the report files, the maven build process is terminated as well. 

We currently have to rely on the `exec` goal to fork the gatling-report call, so there is at least a clumsy workaround. Still calling `System.exit()` is not a polite way to finish execution and is generally frowned upon.

**Comment by bdelbosc** [comment]
System.exit is only used on error when you submit a bad output directory or when asking for help, so I don't see why it prevents you to use exec-maven-plugin java.
Anyway if you want to submit a PR, you are welcome.

**Comment by stolp** [comment]
You are right about the gatling-report sources, the real culprit lies in the implementation of capsule (taken from Capsule.java):

```
    public static final void main(String[] args) {
        System.exit(main0(args));
    }

```

I think there is not much to do about this (main0 is chosen to be private static), so please feel free to close this issue.

Thanks for providing this nice tool btw. :)

**Comment by bdelbosc** [comment]
ok thanks for the feedback
