### ISSUE TITLE
Simulation Log Unparseable?

### ISSUE THREAD

**Issue by deech** [nuxeo/gatling-report#7]
Hi,
First off, thanks for making this package. It's a real timesaver!

I have a `simulation.log` file that looks something like:

```
RUN TEST        test    1470314357550       2.0
USER    TEST Test   1   START   1470314358333   1470314358333
USER    TEST Test   2   START   1470314358356   1470314358356
USER    TEST Test   3   START   1470314358356   1470314358356
USER    TEST Test   4   START   1470314358356   1470314358356
...
REQUEST TEST Test   2       sendTESTS   1470314361728   1470314363675   OK   
USER    TEST Test   2   END 1470314358356   1470314363743
REQUEST TEST Test   12      sendTESTS   1470314362441   1470314364144   KO  status.find.is(204), but actually found 500
REQUEST TEST Test   6       sendTESTS   1470314362103   1470314364217   OK   
USER    TEST Test   6   END 1470314358356   1470314364223
REQUEST TEST Test   27      sendTESTS   1470314363157   1470314364229   KO  status.find.is(204), but actually found 500
REQUEST TEST Test   5       sendTESTS   1470314362038   1470314364241   OK   
USER    TEST Test   5   END 1470314358356   1470314364242
...
```

When I try to get some CSV using:

```
java -jar target/gatling-report-1.0-SNAPSHOT-capsule-fat.jar simulation.log 
```

I get:

```
08:13:07,969 INFO  [App] Parsing simulation.log
simulation  scenario    maxUsers    request start   startDate   duration    end count   successCount    errorCount  min p50 p95 p99 max avg stddev  rps apdex   rating
_all    _all    0   _all    0   1969-12-31 18:00:00 0.00    0   0   0   0   0   0   0   0   0   NaN 0   NaN 0.00    Unacceptable
```

Am I doing something wrong?

**Comment by bdelbosc** [comment]
Hi,
the format of the file is weird, the 2 first columns are missing (simulation name and thread id).
Are you using the default Gatling 2.x configuration ?
ben

**Comment by atroch** [comment]
Hi,
I'm having same issue. Gatling 2.2.2, default conf.

**Comment by tomdutki** [comment]
Unfortunately
"Beware that the format of this file is an implementation details of the FileDataWriter/FileDataReader combo, so it might be subject to changes."
In file SimulationParser.java I provisionally remaped indexes of row columns

    private static final int SCENARIO = 1;
    private static final int SIMULATION_NAME = 3;
    private static final int SCENARIO_ACTION = 0;
    private static final int SIMULATION_START_DATE = 4;
    private static final int USER_ACTION = 3;
    private static final int REQUEST_NAME = 4;
    private static final int VERSION = 6;
    private static final int REQUEST_START_DATE = 5;
    //private static final int END_DATE = 7;
    private static final int REQUEST_END_DATE = 6;
    private static final int REQUEST_RESULT = 7;

            scenario = line.get(SCENARIO);
            switch (line.get(SCENARIO_ACTION)) {
                case RUN:
                    String version = line.get(VERSION);
                    if (!version.startsWith("2.")) {
                        return invalidFile();
                    }
                    ret.setSimulationName(line.get(SIMULATION_NAME));
                    ret.setStart(Long.parseLong(line.get(SIMULATION_START_DATE)));
                    break;
                case REQUEST:
                    name = line.get(REQUEST_NAME);
                    start = Long.parseLong(line.get(REQUEST_START_DATE));
                    end = Long.parseLong(line.get(REQUEST_END_DATE));
                    success = OK.equals(line.get(REQUEST_RESULT));
                    ret.addRequest(scenario, name, start, end, success);
                    break;
                case USER:
                    switch (line.get(USER_ACTION)) {
                        case START:
                            ret.addUser(scenario);
                            break;
                        case END:
                            ret.endUser(scenario);
                            break;
                    }
                    break;
            }

So far it works, but in project is a lot of test files with obsolete format so I need to ignore test classes.

**Comment by dkgawande** [comment]
Hi Deech, did you manage to fix the error? I am using Gatling 2.2.2.

**Comment by elkorman15** [comment]
hallo @dkgawande have you fix the error?

**Comment by elkorman15** [comment]
I modified the SimulationParser.java file and now it's going!
`while ((line = reader.readNext()) != null) {
            if (line.size() <= 2) {
                invalidFile();
            }
            scenario = line.get(1);//0
            switch (line.get(0)) {//2
                case RUN:
                    String version = line.get(6);//5
                    if (!version.startsWith("2.")) {
                        return invalidFile();
                    }
                    ret.setSimulationName(line.get(3)); //1
                    ret.setStart(Long.parseLong(line.get(4)));//3
                    break;
                case REQUEST:
                    name = line.get(4);//4
                    start = Long.parseLong(line.get(5));//6
                    end = Long.parseLong(line.get(6));//8
                    success = OK.equals(line.get(7));//9
                    ret.addRequest(scenario, name, start, end, success);
                    break;
                case USER:
                    switch (line.get(3)) {//3
                        case START:
                            ret.addUser(scenario);
                            break;
                        case END:
                            ret.endUser(scenario);
                            break;
                    }
                    break;
            }
        }`

**Comment by coverbeck** [comment]
I am running into an error with Gatling 3 files:

```
Exception in thread "Thread-0" java.lang.NumberFormatException: For input string: "OK"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at org.nuxeo.tools.gatling.report.SimulationParserV3.getRequestEnd(SimulationParserV3.java:64)
	at org.nuxeo.tools.gatling.report.SimulationParser.parse(SimulationParser.java:75)
	at org.nuxeo.tools.gatling.report.App.parseSimulationFile(App.java:66)
	at org.nuxeo.tools.gatling.report.App.lambda$parseSimulationFiles$0(App.java:59)
	at java.util.ArrayList.forEach(ArrayList.java:1255)
	at org.nuxeo.tools.gatling.report.App.parseSimulationFiles(App.java:59)
	at org.nuxeo.tools.gatling.report.App.run(App.java:53)
	at java.lang.Thread.run(Thread.java:748)
```

I'll try tweaking the code; I tried changing the index being used in  `getRequestEnd`, but then I ran into another error.

**Comment by MaksSieve** [comment]
> I am running into an error with Gatling 3 files:
> 
> ```
> Exception in thread "Thread-0" java.lang.NumberFormatException: For input string: "OK"
> 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
> 	at java.lang.Long.parseLong(Long.java:589)
> 	at java.lang.Long.parseLong(Long.java:631)
> 	at org.nuxeo.tools.gatling.report.SimulationParserV3.getRequestEnd(SimulationParserV3.java:64)
> 	at org.nuxeo.tools.gatling.report.SimulationParser.parse(SimulationParser.java:75)
> 	at org.nuxeo.tools.gatling.report.App.parseSimulationFile(App.java:66)
> 	at org.nuxeo.tools.gatling.report.App.lambda$parseSimulationFiles$0(App.java:59)
> 	at java.util.ArrayList.forEach(ArrayList.java:1255)
> 	at org.nuxeo.tools.gatling.report.App.parseSimulationFiles(App.java:59)
> 	at org.nuxeo.tools.gatling.report.App.run(App.java:53)
> 	at java.lang.Thread.run(Thread.java:748)
> ```
> I'll try tweaking the code; I tried changing the index being used in `getRequestEnd`, but then I ran into another error.
+1

**Comment by bdelbosc** [comment]
Hi, yes the format of the report file depends on the Gatling version. gatling-report 4.0 works with reports from Gatling  2.3.1, 2.1.7, 3.0.0 and 3.2.1.
other versions might requires adaptation.
Regards.
